Added motoman_mh5 IKfast plugin
ros-industrial/motoman_experimental pull request #27
Opened 2017-07-05 19:24 UTC by nsnitish

2017-07-05 19:25 UTC, nsnitish commented
@shaun-edwards! Please have a look

2017-07-06 02:30 UTC, shaun-edwards commented
@nsnitish,  The failure occurs in the indigo build.  The problem is an ambiguous call to `isnan`.  The easiest solution is to add the `std::` namespace to the call of `isnan` in `*_ikfast_solver, as was done [here](https://github.com/uos/katana_driver/commit/875324a96c9be1d221b4db951c4df8a1c3ff0c4e).

This would require changing an auto-generated ikfast file (not desirable).

@gavanderhoorn solved this problem, this [way](https://github.com/ros-industrial/fanuc/commit/c8eb156d14fb96b932c90a19e61181a0e04b465a).  However, when I use this, I get the following error:
```
motoman_mh5_manipulator_ikfast_solver.cpp:1631:77: error: ‘>>’ should be ‘> >’ within a nested template argument list
                                                                       IkReal>>

<snip>

motoman_mh5_manipulator_ikfast_moveit_plugin.cpp:1222:36: error: ‘>>’ should be ‘> >’ within a nested template argument list
   std::vector<IkSolutionList<IkReal>> solution_set;
```
This doesn't occur in the fanuc package, because it's `*_ikfast_solver.cpp` and `*_moveit_plugin.cpp` do not have examples of `>>`.  I'm not sure why this is.

Unless @gavanderhoorn provides some insight, I suggest adding `std::` to each `isnan` call.

2017-07-06 07:21 UTC, gavanderhoorn commented
@shaun-edwards wrote:
> This doesn't occur in the fanuc package, because it's `*_ikfast_solver.cpp` and `*_moveit_plugin.cpp` do not have examples of `>>`.  I'm not sure why this is.

The IK plugins in `fanuc` are rather old (they're overdue for some updates: ros-industrial/fanuc#123), so the `>>` and `isnan(..)` stuff was probably added to the IKFast template after they were generated.

2017-07-08 05:36 UTC, nsnitish commented
@shaun-edwards! Can you have a look?

2017-07-08 22:10 UTC, shaun-edwards requested changes
Small changes requested.  Then it looks like we are good to go.

2017-07-08 22:10 UTC, shaun-edwards commented on motoman_mh5_ikfast_manipulator_plugin/package.xml
> +<?xml version='1.0' encoding='ASCII'?>
Please clean up/delete the comments in this file.

2017-07-08 22:10 UTC, shaun-edwards commented on motoman_mh5_ikfast_manipulator_plugin/package.xml
> +  <maintainer email="nitishsharma@todo.todo">nitishsharma</maintainer>
Add your PlusOne email here.

2017-07-08 22:10 UTC, shaun-edwards commented on motoman_mh5_ikfast_manipulator_plugin/package.xml
> +  <license>TODO</license>
Set the license to Apache 2.0

2017-07-09 18:10 UTC, nsnitish commented
@shaun-edwards! Are there any other changes required?

2017-07-09 18:30 UTC, shaun-edwards approved these changes
Looks good.  Thanks for the contribution!

2017-07-09 18:31 UTC, merged

2017-07-09 20:56 UTC, gavanderhoorn commented
Just curious: the generated `motoman_mh5_manipulator_ikfast_solver.cpp` appears to be 4.3MB (!) in size. That seems a tad excessive.

@nsnitish: can you describe how you generated this solver?

2017-07-09 20:58 UTC, gavanderhoorn commented
Two other comments:

 - `update_ikfast_plugin.sh` contains references to paths local to @nsnitish' machine (`/home/nitishsharma/..`)
 - the introduced pkg does not follow the layout and formatting of other MoveIt IKFast plugins we have (in the ABB and Fanuc repositories fi). Would we want to harmonize across all ros-i repositories and update this one?

2017-07-09 21:07 UTC, nsnitish commented
@gavanderhoorn! I followed [this tutorial](http://docs.ros.org/kinetic/api/moveit_tutorials/html/doc/ikfast_tutorial.html).

2017-07-09 21:30 UTC, gavanderhoorn commented
And you installed OpenRAVE from source? Can you tell me which commit your `openrave` clone is at?

Which links did you select for `baselink` and `eelink`?

I've just run the same command, but using the `personalrobotics/ros-openrave` Docker image, and the generated IK solver is 103KB. That is quite a significant difference.

Running the iktests (with a different generator command) I get the following output:
```
testik, success rate: 1.000000, wrong solutions: 0.000000, no solutions: 0.000000, missing solution: 0.455000
```

That is not really good: basically the solver can only find a solution for about 50% of the queries (but if it finds one, they are all ok).

Have you ran the OpenRAVE iktests?

2017-07-10 03:11 UTC, nsnitish commented
@gavanderhoorn! Thanks for pointing this out. It's kinda weird but the problem is in the [clang formatting](http://moveit.ros.org/documentation/contributing/code/) that I used. Auto-generated file is 571 KB.

I haven't ran the OpenRAVE iktests but I have tested the plugin with [moveit_kinematics_tests](https://github.com/ros-planning/moveit_kinematics_tests).

2017-07-10 03:18 UTC, shaun-edwards commented
It's odd that ikfast wouldn't be better at solving the mh5 kinematics.  It is a standard industrial manipulator with a spherical wrist.  If ikfast has trouble with this robot, then I would expect it to have trouble with a lot of other robots we have.

2017-07-10 07:04 UTC, gavanderhoorn commented
@nsnitish wrote:
> @gavanderhoorn! Thanks for pointing this out. It's kinda weird but the problem is in the [clang formatting](http://moveit.ros.org/documentation/contributing/code/) that I used. Auto-generated file is 571 KB.

So that would mean that the formatting introduced about 3.8MB of additional characters.

> I haven't ran the OpenRAVE iktests but I have tested the plugin with [moveit_kinematics_tests](https://github.com/ros-planning/moveit_kinematics_tests).

And that all succeeded?

It seems strange that OpenRAVE's own tests would indicate this low a success rate, and then 'our' test does succeed. It's not impossible though, as I've seen other people claim that `iktests` failed horribly for them, but the solver worked 'alright'.

But I think this deserves some more investigation.

@nsnitish: could you also answer my other questions please?

2017-07-10 07:06 UTC, gavanderhoorn commented
@shaun-edwards:
> It's odd that ikfast wouldn't be better at solving the mh5 kinematics.  It is a standard industrial manipulator with a spherical wrist.  If ikfast has trouble with this robot, then I would expect it to have trouble with a lot of other robots we have.

I agree that it probably should be better, but I'm just reporting what I'm seeing.

If the generated reporter is really not that good, we should at least mention that somewhere.

Related: ros-industrial/fanuc#99.

2017-07-11 00:14 UTC, nsnitish commented
@gavanderhoorn! 
1. I am using the [latest stable commit of openRAVE](https://github.com/rdiankov/openrave/tree/latest_stable), sympy version 1.1. 

2. baselink is 0 and eelink is 6. 

3. Results from moveit_kinematics_tests for motoman_mh5
![screenshot from 2017-07-10 19-10-00](https://user-images.githubusercontent.com/24629206/28045562-6faf62b4-65a3-11e7-918a-45ba5eb1f5aa.png)

2017-07-11 15:29 UTC, gavanderhoorn commented
@nsnitish wrote:

> 1. I am using the [latest stable commit of openRAVE](https://github.com/rdiankov/openrave/tree/latest_stable), 

wow. That is quite old: [latest_stable...master](https://github.com/rdiankov/openrave/compare/latest_stable...master).

> sympy version 1.1. 

I'm surprised this works. But maybe there is such a difference between `latest-stable` and `master` that my previous experience with `sympy` doesn't apply here.

> baselink is 0 and eelink is 6.

ok.

> Results from moveit_kinematics_tests for motoman_mh5
![screenshot from 2017-07-10 19-10-00](https://user-images.githubusercontent.com/24629206/28045562-6faf62b4-65a3-11e7-918a-45ba5eb1f5aa.png)

Ok. This doesn't tell me much but it looks like most tests are succeeding.

I still believe this deserves more investigation, as it's at least weird that OpenRAVE's own test claims that 50% of IK requests fail, while 'our' tests indicate that (almost) everything is fine.

2017-07-11 15:30 UTC, gavanderhoorn commented
@nsnitish wrote:
> @gavanderhoorn! Thanks for pointing this out. It's kinda weird but the problem is in the [clang formatting](http://moveit.ros.org/documentation/contributing/code/) that I used. Auto-generated file is 571 KB.

this is unfortunate actually: we don't require clang-formatting in this repository, and it seems strange to do that to auto-generated code in the first place. But it's been merged, so lets not concern ourselves with that any more.